# Must pass on the PR before a PR gets added to the queue
pr_status = []

# Must pass on the merge with the master branch
status = [
    "CI"
]

cut_body_after = "<details>"

delete_merged_branches = true

